"""Phase 2 initial schema: users, analyses, claims, evidence,
source_credibility_registry, usage_ledger.

Hand-written (not autogenerated) — no live Postgres server exists in the dev
environment this was built in to diff against; verified instead by running
`alembic upgrade head` / `downgrade base` against a throwaway SQLite file.
Column-for-column, this mirrors app/models/*.py exactly.

Revision ID: 0001
Revises:
Create Date: 2026-08-13

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    # Uuid() is cross-dialect (native UUID on Postgres, CHAR(32) on SQLite),
    # matching app/db/base.py's UUIDPrimaryKeyMixin.
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "users",
        _uuid_column("id", primary_key=True),
        sa.Column("phone_number_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("phone_number_hash", sa.String(64), nullable=False),
        sa.Column("preferred_language", sa.String(5), nullable=False, server_default="en"),
        sa.Column("auto_detect_language", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("privacy_mode", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("phone_number_hash", name="uq_users_phone_number_hash"),
    )
    op.create_index("ix_users_phone_number_hash", "users", ["phone_number_hash"])

    op.create_table(
        "analyses",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        sa.Column("input_type", sa.String(20), nullable=False, server_default="text"),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("content_fingerprint", sa.String(64), nullable=False),
        sa.Column("source_wamid", sa.String(128), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("overall_result", sa.String(30), nullable=True),
        sa.Column("language", sa.String(5), nullable=False),
        sa.Column("privacy_mode_snapshot", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(50), nullable=True),
        sa.Column("processing_duration_ms", sa.Integer(), nullable=True),
        sa.Column("evidence_search_count", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("llm_tool_call_count", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("budget_limit_hit", sa.Boolean(), nullable=False, server_default=sa.false()),
        _uuid_column("reused_from_analysis_id", nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reused_from_analysis_id"], ["analyses.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("source_wamid", name="uq_analyses_source_wamid"),
    )
    op.create_index("ix_analyses_user_id", "analyses", ["user_id"])
    op.create_index("ix_analyses_content_fingerprint", "analyses", ["content_fingerprint"])
    op.create_index("ix_analyses_status", "analyses", ["status"])
    op.create_index("ix_analyses_user_created", "analyses", ["user_id", "created_at"])

    op.create_table(
        "claims",
        _uuid_column("id", primary_key=True),
        _uuid_column("analysis_id", nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("claim_order", sa.SmallInteger(), nullable=False),
        sa.Column("result", sa.String(30), nullable=False),
        sa.Column("investigation_complete", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("incomplete_reason", sa.String(30), nullable=True),
        sa.Column("claim_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("media_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("evidence_strength", sa.Numeric(4, 3), nullable=True),
        sa.Column("reasoning_text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(30), nullable=True),
        sa.Column("evidence_tier_met", sa.SmallInteger(), nullable=True),
        sa.Column("policy_override_applied", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_claims_analysis_id", "claims", ["analysis_id"])
    op.create_index("ix_claims_analysis_order", "claims", ["analysis_id", "claim_order"])

    op.create_table(
        "evidence",
        _uuid_column("id", primary_key=True),
        _uuid_column("claim_id", nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_domain", sa.String(255), nullable=True),
        sa.Column("source_title", sa.Text(), nullable=True),
        sa.Column("publisher_name", sa.String(255), nullable=True),
        sa.Column("stance", sa.String(20), nullable=False),
        sa.Column("relevance_score", sa.Numeric(4, 3), nullable=True),
        sa.Column("credibility_score", sa.Numeric(4, 3), nullable=True),
        sa.Column("credibility_tier", sa.String(30), nullable=True),
        sa.Column("snippet_text", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_evidence_claim_id", "evidence", ["claim_id"])
    op.create_index("ix_evidence_source_domain", "evidence", ["source_domain"])

    op.create_table(
        "source_credibility_registry",
        _uuid_column("id", primary_key=True),
        sa.Column("domain", sa.String(255), nullable=False),
        sa.Column("credibility_tier", sa.String(30), nullable=False),
        sa.Column("region", sa.String(10), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("domain", name="uq_source_credibility_registry_domain"),
    )
    op.create_index("ix_source_credibility_registry_domain", "source_credibility_registry", ["domain"])

    op.create_table(
        "usage_ledger",
        _uuid_column("id", primary_key=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("evidence_search_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("llm_tool_call_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("estimated_cost_usd", sa.Numeric(10, 2), nullable=False, server_default="0"),
        sa.Column("circuit_breaker_tripped", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("tripped_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("date", name="uq_usage_ledger_date"),
    )
    op.create_index("ix_usage_ledger_date", "usage_ledger", ["date"])


def downgrade() -> None:
    op.drop_table("usage_ledger")
    op.drop_table("source_credibility_registry")
    op.drop_table("evidence")
    op.drop_table("claims")
    op.drop_table("analyses")
    op.drop_table("users")
