"""Phase 3: media_attachments, safety_gate_events, media_forensics_results,
benchmark_datasets, benchmark_runs.

Hand-written (not autogenerated), same practice as 0001 — no live Postgres
in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

Also documents a non-schema change: `analyses.status` gains a new valid
application-level value, `blocked` (safety-gate short-circuit) — no
migration needed since the column is a plain varchar(20) with no DB-level
CHECK constraint; see docs/database-schema.md.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-14

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "media_attachments",
        _uuid_column("id", primary_key=True),
        _uuid_column("analysis_id", nullable=False),
        sa.Column("whatsapp_media_id", sa.String(128), nullable=False),
        sa.Column("storage_path", sa.String(500), nullable=True),  # always NULL in Phase 3 — no blob storage, see model docstring
        sa.Column("media_type", sa.String(20), nullable=False),
        sa.Column("mime_type", sa.String(100), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256_hash", sa.LargeBinary(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_media_attachments_analysis_id", "media_attachments", ["analysis_id"])

    op.create_table(
        "safety_gate_events",
        _uuid_column("id", primary_key=True),
        _uuid_column("media_attachment_id", nullable=True),
        _uuid_column("analysis_id", nullable=False),
        sa.Column("check_type", sa.String(30), nullable=False),
        sa.Column("outcome", sa.String(20), nullable=False),
        sa.Column("provider_name", sa.String(50), nullable=True),
        sa.Column("reference_id", sa.Text(), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["media_attachment_id"], ["media_attachments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_safety_gate_events_analysis_id", "safety_gate_events", ["analysis_id"])
    op.create_index("ix_safety_gate_events_outcome", "safety_gate_events", ["outcome"])

    op.create_table(
        "media_forensics_results",
        _uuid_column("id", primary_key=True),
        _uuid_column("media_attachment_id", nullable=False),
        sa.Column("tool_name", sa.String(50), nullable=False),
        sa.Column("provider_name", sa.String(50), nullable=False),
        sa.Column("model_version", sa.String(50), nullable=False),
        sa.Column("ai_generated_probability", sa.Numeric(4, 3), nullable=True),
        sa.Column("manipulation_score", sa.Numeric(4, 3), nullable=True),
        sa.Column("raw_output", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["media_attachment_id"], ["media_attachments.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_media_forensics_results_media_attachment_id", "media_forensics_results", ["media_attachment_id"])

    op.create_table(
        "benchmark_datasets",
        _uuid_column("id", primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("modality", sa.String(20), nullable=False),
        sa.Column("language", sa.String(5), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=True),
        sa.Column("source_description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "benchmark_runs",
        _uuid_column("id", primary_key=True),
        _uuid_column("dataset_id", nullable=False),
        sa.Column("tool_name", sa.String(50), nullable=False),
        sa.Column("model_version", sa.String(50), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accuracy_metrics", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["dataset_id"], ["benchmark_datasets.id"]),
    )
    op.create_index("ix_benchmark_runs_dataset_id", "benchmark_runs", ["dataset_id"])


def downgrade() -> None:
    op.drop_table("benchmark_runs")
    op.drop_table("benchmark_datasets")
    op.drop_table("media_forensics_results")
    op.drop_table("safety_gate_events")
    op.drop_table("media_attachments")
