"""Phase 4: url_safety_scans.

Hand-written (not autogenerated), same practice as 0001/0002 — no live
Postgres in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

Migrates the table design already documented in database-schema.md (listed
there as "design-reference-only, not migrated" prior to this phase) —
unchanged from that design.

Also documents a non-schema change: `analyses.input_type` gains real usage
of its already-documented `url` value, and `analyses.input_text` stores the
URL itself (not the fetched page content — see app/agent/url_pipeline.py's
module docstring for why). No migration needed since both columns are
plain varchar/text with no DB-level CHECK constraint.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-13

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "url_safety_scans",
        _uuid_column("id", primary_key=True),
        _uuid_column("analysis_id", nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("risk_level", sa.String(20), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("threat_intel_matches", sa.JSON(), nullable=True),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_url_safety_scans_analysis_id", "url_safety_scans", ["analysis_id"])


def downgrade() -> None:
    op.drop_table("url_safety_scans")
