"""Phase 5a: transcripts.

Hand-written (not autogenerated), same practice as 0001-0003 — no live
Postgres in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

Migrates the table design already documented in database-schema.md (listed
there as "design-reference-only, not migrated" prior to this phase) —
unchanged from that design. Generic across audio-clip transcripts
(AudioPipeline, this migration) and video-extracted-audio transcripts
(VideoPipeline, Phase 5b) — no schema change needed for the latter.

Also documents non-schema changes: `analyses.input_type` gains real usage of
its already-documented `audio` value; `analyses.input_text` stays empty for
audio analyses (the real transcript lives in `transcripts`, not duplicated
into `analyses` — see app/agent/audio_pipeline.py's module docstring).
`media_attachments.media_type='audio'` and
`media_forensics_results.tool_name='audio_voice_detect'` both use
already-documented values, unused until now. No migration needed for any of
these — all are plain varchar/text columns with no DB-level CHECK
constraint.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-13

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "transcripts",
        _uuid_column("id", primary_key=True),
        _uuid_column("media_attachment_id", nullable=False),
        sa.Column("language", sa.String(5), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("engine", sa.String(50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["media_attachment_id"], ["media_attachments.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_transcripts_media_attachment_id", "transcripts", ["media_attachment_id"])


def downgrade() -> None:
    op.drop_table("transcripts")
