"""Phase 5b: video_frames.

Hand-written (not autogenerated), same practice as 0001-0004 — no live
Postgres in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

New table, not previously drafted in database-schema.md (that design set
predates any video work) — see app/models/video_frame.py's docstring for
why it's structured this way (no frame images stored, mirrors `transcripts`).

Also documents non-schema changes: `analyses.input_type` gains real usage of
its already-documented `video` value; `media_attachments.media_type='video'`
and `media_forensics_results.tool_name='video_deepfake'` both use
already-documented values, unused until now. `transcripts` (migrated in
0004) is reused unchanged for video-extracted-audio transcripts — no
video-specific transcript table needed.

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-14

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "video_frames",
        _uuid_column("id", primary_key=True),
        _uuid_column("media_attachment_id", nullable=False),
        sa.Column("frame_timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("detected_language", sa.String(5), nullable=True),
        sa.Column("ocr_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["media_attachment_id"], ["media_attachments.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_video_frames_media_attachment_id", "video_frames", ["media_attachment_id"])


def downgrade() -> None:
    op.drop_table("video_frames")
