"""Phase 6: dashboard_accounts, otp_verifications, audit_log,
media_attachments.retention_expires_at.

Hand-written (not autogenerated), same practice as 0001-0005 — no live
Postgres in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

`dashboard_accounts`/`otp_verifications` migrate the already-designed
tables unchanged (database-schema.md). `audit_log` migrates a table that
was designed since the original architecture pass but never built in any
of Phases 1-5 — decisions.md §9 requires it as "a required, not optional,
MVP component"; Phase 6's dashboard/auth surface is the first one that
genuinely needs it.

`media_attachments` gains `retention_expires_at` (already documented in
database-schema.md, never populated until now) — an ADD COLUMN on an
existing table, not a new mechanism; see app/models/media_attachment.py's
updated docstring and app/agent/retention.py.

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-15

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "dashboard_accounts",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )

    op.create_table(
        "otp_verifications",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        sa.Column("channel", sa.String(20), nullable=False),
        sa.Column("purpose", sa.String(30), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_otp_verifications_user_id", "otp_verifications", ["user_id"])

    op.create_table(
        "audit_log",
        _uuid_column("id", primary_key=True),
        sa.Column("actor_type", sa.String(20), nullable=False),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(50), nullable=True),
        _uuid_column("entity_id", nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"])

    op.add_column("media_attachments", sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("ix_media_attachments_retention_expires_at", "media_attachments", ["retention_expires_at"])


def downgrade() -> None:
    op.drop_index("ix_media_attachments_retention_expires_at", table_name="media_attachments")
    op.drop_column("media_attachments", "retention_expires_at")
    op.drop_table("audit_log")
    op.drop_table("otp_verifications")
    op.drop_table("dashboard_accounts")
