"""Phase 8: scheduled_checks, notifications, analysis_sessions,
explore_claim_clusters, analyses.session_id.

Hand-written (not autogenerated), same practice as 0001-0006 — no live
Postgres in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

`scheduled_checks` implements "Check This Tomorrow" (decisions.md §14) —
backend scheduling/re-check infrastructure only; the proactive WhatsApp
notification SEND remains blocked pending decisions.md §4's three
preconditions (see app/agent/notifications.py). `notifications` is new,
channel-abstract (in_app | whatsapp) infrastructure. `analysis_sessions` is
a NEW table for the "group related analyses" feature — deliberately named
differently from the already-documented, different-purpose
`conversation_sessions` design (WhatsApp flow-state mirror, still not
migrated) — see app/models/analysis_session.py's docstring.
`explore_claim_clusters` has no FK to users/analyses anywhere, by design
(api-design.md's "Structural privacy enforcement").

`analyses` gains `session_id` (nullable FK, ON DELETE SET NULL — deleting a
session must never delete the analyses grouped under it).

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-16

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "analysis_sessions",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_analysis_sessions_user_id", "analysis_sessions", ["user_id"])

    # batch_alter_table: SQLite has no ALTER-ADD-CONSTRAINT support (confirmed
    # by running this migration — a plain add_column + create_foreign_key
    # pair raises NotImplementedError on SQLite); batch mode transparently
    # uses SQLite's recreate-table strategy there while staying a direct,
    # normal ALTER on Postgres. Phase 6's retention_expires_at column never
    # needed this because it had no FK, only a plain column + index.
    with op.batch_alter_table("analyses") as batch_op:
        batch_op.add_column(sa.Column("session_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_analyses_session_id", "analysis_sessions", ["session_id"], ["id"], ondelete="SET NULL"
        )
    op.create_index("ix_analyses_session_id", "analyses", ["session_id"])

    op.create_table(
        "scheduled_checks",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        _uuid_column("source_analysis_id", nullable=True),
        sa.Column("claim_text_snapshot", sa.Text(), nullable=False),
        sa.Column("category", sa.String(30), nullable=True),
        sa.Column("language", sa.String(5), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_result_snapshot", sa.JSON(), nullable=True),
        sa.Column("new_result_snapshot", sa.JSON(), nullable=True),
        sa.Column("credibility_changed", sa.Boolean(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=False, server_default="3"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("notification_status", sa.String(20), nullable=False, server_default="not_sent"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_analysis_id"], ["analyses.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_scheduled_checks_user_id", "scheduled_checks", ["user_id"])
    op.create_index("ix_scheduled_checks_source_analysis_id", "scheduled_checks", ["source_analysis_id"])
    op.create_index("ix_scheduled_checks_status", "scheduled_checks", ["status"])
    op.create_index("ix_scheduled_checks_scheduled_for", "scheduled_checks", ["scheduled_for"])

    op.create_table(
        "notifications",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        sa.Column("notification_type", sa.String(40), nullable=False),
        sa.Column("channel", sa.String(20), nullable=False, server_default="in_app"),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("related_entity_type", sa.String(50), nullable=True),
        _uuid_column("related_entity_id", nullable=True),
        sa.Column("delivery_status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"])

    op.create_table(
        "explore_claim_clusters",
        _uuid_column("id", primary_key=True),
        sa.Column("cluster_fingerprint", sa.String(64), nullable=False),
        sa.Column("representative_claim_text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(30), nullable=True),
        sa.Column("language", sa.String(5), nullable=False),
        sa.Column("credibility_status", sa.String(30), nullable=False),
        sa.Column("credibility_score", sa.Numeric(4, 3), nullable=True),
        sa.Column("source_count", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("check_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("cluster_fingerprint"),
    )
    op.create_index("ix_explore_claim_clusters_cluster_fingerprint", "explore_claim_clusters", ["cluster_fingerprint"])
    op.create_index("ix_explore_claim_clusters_category", "explore_claim_clusters", ["category"])
    op.create_index("ix_explore_claim_clusters_credibility_status", "explore_claim_clusters", ["credibility_status"])
    op.create_index("ix_explore_claim_clusters_last_seen_at", "explore_claim_clusters", ["last_seen_at"])


def downgrade() -> None:
    op.drop_index("ix_explore_claim_clusters_last_seen_at", table_name="explore_claim_clusters")
    op.drop_index("ix_explore_claim_clusters_credibility_status", table_name="explore_claim_clusters")
    op.drop_index("ix_explore_claim_clusters_category", table_name="explore_claim_clusters")
    op.drop_index("ix_explore_claim_clusters_cluster_fingerprint", table_name="explore_claim_clusters")
    op.drop_table("explore_claim_clusters")

    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_table("notifications")

    op.drop_index("ix_scheduled_checks_scheduled_for", table_name="scheduled_checks")
    op.drop_index("ix_scheduled_checks_status", table_name="scheduled_checks")
    op.drop_index("ix_scheduled_checks_source_analysis_id", table_name="scheduled_checks")
    op.drop_index("ix_scheduled_checks_user_id", table_name="scheduled_checks")
    op.drop_table("scheduled_checks")

    op.drop_index("ix_analyses_session_id", table_name="analyses")
    with op.batch_alter_table("analyses") as batch_op:
        batch_op.drop_constraint("fk_analyses_session_id", type_="foreignkey")
        batch_op.drop_column("session_id")

    op.drop_index("ix_analysis_sessions_user_id", table_name="analysis_sessions")
    op.drop_table("analysis_sessions")
