"""Phase 9: admin_users, appeals, moderation_reports, users.is_suspended/
suspended_at/suspended_reason.

Hand-written (not autogenerated), same practice as 0001-0007 — no live
Postgres in the dev environment to diff against; verified by running
`alembic upgrade head` / `downgrade` against a throwaway SQLite file.

`admin_users` is a SEPARATE identity table from `users` (see
app/models/admin_user.py's docstring) — no FK relationship to `users` at
all, by design; admins are internal operators, not WhatsApp end-users.

`appeals.analysis_id` is CASCADE (an appeal has no purpose once its subject
analysis is gone); `appeals.claim_id`/`resolved_by` and
`moderation_reports.target_analysis_id`/`target_explore_cluster_id`/
`resolved_by` are all SET NULL (the report/appeal record itself outlives
its optional reference being cleared, same "explicit Python delete /
null-out in app code, never trust the DB's ON DELETE action" discipline
every table in this codebase already follows — see
app/agent/retention.py's module docstring).

`users` gains three plain columns for admin "Suspend user" (roadmap §9.1) —
no FK, so a plain `add_column` (not `batch_alter_table`) is sufficient, same
as Phase 6's `media_attachments.retention_expires_at` precedent.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-16

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_column(name: str, **kwargs) -> sa.Column:
    return sa.Column(name, sa.Uuid(), **kwargs)


def upgrade() -> None:
    op.create_table(
        "admin_users",
        _uuid_column("id", primary_key=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(20), nullable=False, server_default="admin"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_admin_users_email", "admin_users", ["email"])

    op.create_table(
        "appeals",
        _uuid_column("id", primary_key=True),
        _uuid_column("user_id", nullable=False),
        _uuid_column("analysis_id", nullable=False),
        _uuid_column("claim_id", nullable=True),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        _uuid_column("resolved_by", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolved_by"], ["admin_users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_appeals_user_id", "appeals", ["user_id"])
    op.create_index("ix_appeals_analysis_id", "appeals", ["analysis_id"])
    op.create_index("ix_appeals_claim_id", "appeals", ["claim_id"])
    op.create_index("ix_appeals_status", "appeals", ["status"])

    op.create_table(
        "moderation_reports",
        _uuid_column("id", primary_key=True),
        _uuid_column("reporter_user_id", nullable=False),
        sa.Column("report_type", sa.String(30), nullable=False),
        sa.Column("target_type", sa.String(20), nullable=False),
        _uuid_column("target_analysis_id", nullable=True),
        _uuid_column("target_explore_cluster_id", nullable=True),
        sa.Column("target_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        _uuid_column("resolved_by", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["reporter_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_analysis_id"], ["analyses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_explore_cluster_id"], ["explore_claim_clusters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolved_by"], ["admin_users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_moderation_reports_reporter_user_id", "moderation_reports", ["reporter_user_id"])
    op.create_index("ix_moderation_reports_report_type", "moderation_reports", ["report_type"])
    op.create_index("ix_moderation_reports_target_analysis_id", "moderation_reports", ["target_analysis_id"])
    op.create_index("ix_moderation_reports_status", "moderation_reports", ["status"])

    op.add_column("users", sa.Column("is_suspended", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("users", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("suspended_reason", sa.String(500), nullable=True))


def downgrade() -> None:
    op.drop_column("users", "suspended_reason")
    op.drop_column("users", "suspended_at")
    op.drop_column("users", "is_suspended")

    op.drop_index("ix_moderation_reports_status", table_name="moderation_reports")
    op.drop_index("ix_moderation_reports_target_analysis_id", table_name="moderation_reports")
    op.drop_index("ix_moderation_reports_report_type", table_name="moderation_reports")
    op.drop_index("ix_moderation_reports_reporter_user_id", table_name="moderation_reports")
    op.drop_table("moderation_reports")

    op.drop_index("ix_appeals_status", table_name="appeals")
    op.drop_index("ix_appeals_claim_id", table_name="appeals")
    op.drop_index("ix_appeals_analysis_id", table_name="appeals")
    op.drop_index("ix_appeals_user_id", table_name="appeals")
    op.drop_table("appeals")

    op.drop_index("ix_admin_users_email", table_name="admin_users")
    op.drop_table("admin_users")
